# ESLint configuration for CEX Exchange
root: true

env:
  browser: true
  es2021: true
  node: true

extends:
  - eslint:recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  # 错误预防
  no-console: warn
  no-debugger: error
  no-alert: warn
  no-unused-vars: error
  no-undef: error
  
  # 代码风格
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
    
  # 最佳实践
  eqeqeq: error
  curly: error
  no-var: error
  prefer-const: error
  arrow-spacing: error
  
  # 函数
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
    
  # 对象
  object-curly-spacing:
    - error
    - always
    
  # 数组
  array-bracket-spacing:
    - error
    - never
    
  # 注释
  spaced-comment:
    - error
    - always

globals:
  MarketDataManager: readonly
  WebSocket: readonly
  fetch: readonly
  
ignorePatterns:
  - node_modules/
  - dist/
  - build/
  - '*.min.js'