[build]
  base = "frontend/web"
  publish = "out"
  command = "npm run build && npm run export"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://cex-backend.onrender.com"
  NEXT_PUBLIC_WS_URL = "wss://cex-backend.onrender.com"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/api/*"
  to = "https://cex-backend.onrender.com/:splat"
  status = 200
  force = true

[dev]
  framework = "#static"
  targetPort = 3000
