[build]
builder = "NIXPACKS"
# 构建市场数据聚合服务
cmd = "cd backend/market-aggregator && go build -o main cmd/server/main.go"

[deploy]
startCommand = "cd backend/market-aggregator && ./main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 300

[environments.production]
[environments.production.variables]
PORT = "8080"
GIN_MODE = "release"
BINANCE_BASE_URL = "https://api.binance.com"
COINGECKO_BASE_URL = "https://api.coingecko.com/api/v3"
CORS_ORIGINS = "*"
LOG_LEVEL = "info"
CACHE_DEFAULT_EXPIRATION = "30s"
CACHE_CLEANUP_INTERVAL = "60s"
RATE_LIMIT_REQUESTS_PER_MINUTE = "100"
RATE_LIMIT_REQUESTS_PER_HOUR = "1000"
# 数据库连接（可选）
# REDIS_URL = "${{ REDIS_URL }}"
# DATABASE_URL = "${{ DATABASE_URL }}"

[environments.staging]
[environments.staging.variables]
PORT = "8080"
GIN_MODE = "debug"
LOG_LEVEL = "debug"
CORS_ORIGINS = "*"
BINANCE_BASE_URL = "https://testnet.binance.vision"
COINGECKO_BASE_URL = "https://api.coingecko.com/api/v3"
